FROM python:3.6.1-slim

MAINTAINER Douglas Miranda <douglasmirandasilva@gmail.com>
MAINTAINER Douglas Soares de Andrade <contato@douglasandrade.com>

RUN apt-get update
RUN groupadd -r taiga && useradd -r -g taiga taiga

RUN apt-get install -y build-essential binutils-doc autoconf flex bison \
    libjpeg-dev libfreetype6-dev zlib1g-dev libzmq3-dev libgdbm-dev \
    libncurses5-dev automake libtool libffi-dev curl gettext \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install -r requirements.txt

# local.py and checkdb.py and celery
# using gevent to run taiga gunicorn (workers)
# using gevent on celery (workers)
RUN pip install django-environ==0.4.0 gevent==1.1.2 django-anymail==0.5
